POST http://localhost:8080/api/products?hl=id
Content-Type: application/json
Accept-Language: de

{
  "brand": "ISung",
  "name": "ISung 17",
  "type": "OFFICIAL",
  "color": "red",
  "items": [
    {"sku": ""}
  ]
}

###
